In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import openexplorer as oe
import numpy as np
from simtk import unit
from simtk.openmm import app

# Movement

In [3]:
topology = msm.convert('alanine_dipeptide.pdb', to_form='openmm.Topology')
forcefield = app.ForceField('amber10.xml', 'amber10_obc.xml')
system = forcefield.createSystem(topology, constraints=app.HBonds, nonbondedMethod=app.NoCutoff)
explorer = oe.Explorer(topology, system, platform='CUDA')

In [4]:
positions = msm.get('alanine_dipeptide.pdb', coordinates=True)[0]
explorer.set_coordinates(positions)

In [5]:
explorer_init = explorer.replicate()
msm.translate(explorer_init, [-1.0, 0.0, 0.0]*unit.nanometers)

## Random shifts in cartesian coordinates

In [6]:
msm.view([explorer_init, explorer])

NGLWidget()

In [7]:
explorer.move.cartesian_shifts.show_parameters()

|                | parameters              |
|:---------------|:------------------------|
| mode_atoms     | random                  |
| mode_steps     | random                  |
| atom_indices   | [ 0  1  2 ... 19 20 21] |
| n_random_atoms | 1                       |
| step_size      | 0.25 nm                 |

In [8]:
explorer.move.cartesian_shifts.run()

In [9]:
explorer.move.cartesian_shifts.atoms_moved

array([14])

In [14]:
aa = msm.get(explorer, target='molecule', atom_index=True)

In [15]:
aa[0]

array([0, 1, 2, ..., 19, 20, 21], dtype=object)

In [12]:
msm.info(explorer)

[0 1 2 ... 19 20 21]
object


IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
msm.info(explorer, target='atom', selection=[21])

In [ ]:
explorer.move.cartesian_shifts.shifts_moved

In [ ]:
aa = msm.convert(explorer)

In [ ]:
msm.view([explorer_init, explorer])

In [ ]:
explorer.move.cartesian_shifts.set_parameters(selection='atom_name=="C"', mode_atoms='all', mode_steps='rmsd',
                                             step_size=0.3*unit.nanometers)

In [ ]:
explorer.move.cartesian_shifts.show_parameters()

In [ ]:
explorer.set_coordinates(positions)

In [ ]:
explorer.move.cartesian_shifts()

In [ ]:
explorer.move.cartesian_shifts.atoms_moved

In [ ]:
explorer.move.cartesian_shifts.shifts_moved

In [ ]:
msm.view([explorer_init, explorer])

## Random shifts in dihedral angles

In [ ]:
explorer.set_coordinates(positions)

In [ ]:
msm.view([explorer_init, explorer])

In [ ]:
msm.get_dihedral_angles(explorer, dihedral_angle='phi-psi')

In [ ]:
explorer.move.dihedral_shifts.show_parameters()

In [ ]:
explorer.move.dihedral_shifts()

In [ ]:
explorer.move.dihedral_shifts.quartets_moved

In [ ]:
explorer.move.dihedral_shifts.shifts_moved

In [ ]:
msm.get_dihedral_angles(explorer, dihedral_angle='phi-psi')

In [ ]:
msm.view([explorer_init, explorer])