In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import openexplorer as oe
import numpy as np
from simtk import unit
from simtk.openmm import app

# Movement

In [3]:
topology = msm.convert('alanine_dipeptide.pdb', to_form='openmm.Topology')
forcefield = app.ForceField('amber10.xml', 'amber10_obc.xml')
system = forcefield.createSystem(topology, constraints=app.HBonds, nonbondedMethod=app.NoCutoff)
explorer = oe.Explorer(topology, system, platform='CUDA')

In [4]:
positions = msm.get('alanine_dipeptide.pdb', coordinates=True)[0]
explorer.set_coordinates(positions)

In [5]:
explorer_init = explorer.replicate()
msm.translate(explorer_init, [-1.0, 0.0, 0.0]*unit.nanometers)

## Random shifts in cartesian coordinates

In [6]:
msm.view([explorer_init, explorer])

NGLWidget()

In [7]:
explorer.move.cartesian_shifts.show_parameters()

|                | parameters              |
|:---------------|:------------------------|
| mode_atoms     | random                  |
| mode_steps     | random                  |
| atom_indices   | [ 0  1  2 ... 19 20 21] |
| n_random_atoms | 1                       |
| step_size      | 0.25 nm                 |

In [8]:
explorer.move.cartesian_shifts.run()

In [9]:
explorer.move.cartesian_shifts.atoms_moved

array([15])

In [10]:
msm.info(explorer, target='atom', selection=explorer.move.cartesian_shifts.atoms_moved)

In [11]:
explorer.move.cartesian_shifts.shifts_moved

Quantity(value=array([[ 0.02657894, -0.18566715,  0.13848521]]), unit=nanometer)

In [12]:
msm.view([explorer_init, explorer])

NGLWidget()

In [13]:
explorer.move.cartesian_shifts.set_parameters(selection='atom_name=="C"', mode_atoms='all', mode_steps='rmsd',
                                             step_size=0.3*unit.nanometers)

In [14]:
explorer.move.cartesian_shifts.show_parameters()

|                | parameters   |
|:---------------|:-------------|
| mode_atoms     | all          |
| mode_steps     | rmsd         |
| atom_indices   | [ 4 14 18]   |
| n_random_atoms | 0            |
| step_size      | 0.3 nm       |

In [15]:
explorer.set_coordinates(positions)

In [16]:
explorer.move.cartesian_shifts()

In [17]:
explorer.move.cartesian_shifts.atoms_moved

array([ 4, 14, 18])

In [18]:
explorer.move.cartesian_shifts.shifts_moved

Quantity(value=array([[ 0.06707246, -0.08941111, -0.09937781],
       [-0.11090412, -0.00025034,  0.1752431 ],
       [ 0.09960182, -0.1157005 ,  0.03624813]]), unit=nanometer)

In [19]:
msm.view([explorer_init, explorer])

NGLWidget()

## Random shifts in dihedral angles

In [20]:
explorer.set_coordinates(positions)

In [21]:
msm.view([explorer_init, explorer])

NGLWidget()

In [22]:
msm.get_dihedral_angles(explorer, dihedral_angle='phi-psi')

Quantity(value=array([[-179.99999499, -179.99999499]]), unit=degree)

In [24]:
explorer.move.dihedral_shifts.show_parameters()

|                 | parameters      |
|:----------------|:----------------|
| mode_angles     | random          |
| mode_steps      | random          |
| quartets        | [[ 4  6  8 14]  |
|                 |  [ 6  8 14 16]] |
| n_random_angles | 1               |
| step_size       | 180.0 deg       |

In [25]:
explorer.move.dihedral_shifts()

In [26]:
explorer.move.dihedral_shifts.quartets_moved

array([1])

In [27]:
explorer.move.dihedral_shifts.shifts_moved

Quantity(value=array([-110.57773739]), unit=degree)

In [28]:
msm.get_dihedral_angles(explorer, dihedral_angle='phi-psi')

Quantity(value=array([[-179.99999499,   69.4222576 ]]), unit=degree)

In [29]:
msm.view([explorer_init, explorer])

NGLWidget()